name: Automates tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose option
        required: true
        default: first_test
        type: choice
        options:
          - first_test
          - ldskjsd
          - sdlkjsdf

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Set up dependancies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
