name: Automates tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose option
        required: true
        default: smoke
        type: choice
        options:
          - smoke
          - regression
          - failed

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Set up dependancies
        run: pip install -r requirements.txt
      - name: Run smoke tests
        if: "github.event.inputs.deployment_target == 'smoke'"
        run: pytest -m smoke --alluredir=allure-results
      - name: Run regression tests
        if: "github.event.inputs.deployment_target == 'regression'"
        run: pytest -m regression --alluredir=allure-results
      - name: Run failed tests
        if: "github.event.inputs.deployment_target == 'failed'"
        run: pytest -m failed --alluredir=allure-results
      - name: Save allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results
          retention-days: 1
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft' # See 'Supported distributions' for available options
          java-version: '17'
      - run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.23.1/allure-2.23.1.tgz && sudo tar -zxvf allure-2.23.1.tgz -C /opt/ && sudo ln -s /opt/allure-2.23.1/bin/allure /usr/bin/allure
      - run: allure generate -c allure-results -o allure-report
      - name: Save allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
          retention-days: 1
