name: Automates tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose option
        required: true
        default: smoke
        type: choice
        options:
          - smoke
          - regression
          - failed

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Set up dependancies
        run: pip install -r requirements.txt
      - name: Run smoke tests
        if: "github.event.inputs.deployment_target == 'smoke'"
        run: pytest -m smoke --alluredir=allure-results
      - name: Run regression tests
        if: "github.event.inputs.deployment_target == 'regression'"
        run: pytest -m regression --alluredir=allure-results
      - name: Run failed tests
        if: "github.event.inputs.deployment_target == 'failed'"
        run: pytest -m failed --alluredir=allure-results
